name: CI

on:
  pull_request:
    branches:
      - "**"
  workflow_call: # Needed to make this a reusable workflow for releasing artifacts https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_dispatch: # To allow starting the workflow manually in the web ui

permissions:
  contents: read

jobs:
  CI:
    timeout-minutes: 30 
    strategy:
      matrix:
        image: [ubuntu-22.04, ubuntu-22.04-arm]
    runs-on:
      - ${{matrix.image}}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.3
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      # Prepare build dependencies
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@47f4dd75f027bd6cfe06f3dc15ddfcb07acc7e4e # 1.74.0
        with:
          components: rustfmt, clippy
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.16.0
      - name: Apt update
        run: sudo apt update
      - name: Install gcc
        run: sudo apt install -y build-essential
      - name: Install SPE libraries
        run: |
          sudo apt install -y \
            libdw-dev \
            libelf-dev \
            libcapstone-dev \
            zlib1g-dev \
            liblzma-dev \
            libbz2-dev \
            libzstd-dev \
            libdwarf-dev \
            linux-headers-$(uname -r) \
            libc6-dev
          
      # - name: Find unistd_64.h
      #   run: |
      #     echo "Searching for unistd_64.h..."
      #     sudo find / -name "unistd_64.h" 2>/dev/null
      #     echo "Kernel version:"
      #     uname -r
      #     echo "Contents of linux-headers directory:"
      #     ls -la /usr/src/linux-headers-$(uname -r)
      #     echo "Contents of asm directory:"
      #     ls -la /usr/src/linux-headers-$(uname -r)/arch/arm64/include/asm/ || echo "asm directory not found"

      # Tests and static analysis
      - name: Set perf_event_paranoid to 0
        run: echo 0 | sudo tee /proc/sys/kernel/perf_event_paranoid
      # Build and upload release artifacts
      - name: Build release artifacts
        run: |
          rustup target add $(arch)-unknown-linux-gnu
          case $(arch) in
            aarch64)
            sudo apt-get install -y \
                libelf-dev \
                libdw-dev \
                libcapstone-dev \
                zlib1g-dev \
                liblzma-dev \
                libbz2-dev \
                libzstd-dev \
                gcc-aarch64-linux-gnu \
                g++-aarch64-linux-gnu \
                libstdc++-11-dev \
                libgcc-11-dev

              echo "Building for aarch64 architecture"
              cargo build --target aarch64-unknown-linux-gnu
              ;;
            *)
              echo "Unsupported architecture: $(arch)"
              exit 1
              ;;
          esac

      - name: Link status
        run: ldd target/$(arch)-unknown-linux-gnu/debug/aperf

      # - name: Archive release artifacts
      #   run: tar -zcvf artifacts.tar.gz -C target/$(arch)-unknown-linux-musl/release aperf
      # - name: Upload x86_64 release artifacts
      #   uses: actions/upload-artifact@v4
      #   if: ${{ matrix.image == 'ubuntu-24.04' }}
      #   with:
      #     name: x86_64-release-artifacts
      #     path: artifacts.tar.gz
      # - name: Upload aarch64 release artifacts
      #   uses: actions/upload-artifact@v4
      #   if: ${{ matrix.image == 'ubuntu-24.04-arm' }}
      #   with:
      #     name: aarch64-release-artifacts
      #     path: artifacts.tar.gz
